spring:
  datasource:
    url: jdbc:mysql://www.chobit.com.cn:24338/graindepot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Chobit@666
    driver-class-name: com.mysql.jdbc.Driver
server:
    port: 8007 #
    #context-path: /graindepot-report